# Copyright (c) 2024 Observe. All rights reserved.
# Licensed under the MIT License. See LICENSE file in the project root for full license information.

name: Modify Redis Configuration

on:
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "tombatchelor"
        git config user.email "tombatchelor@observeinc.com"

    - name: Toggle ssl=false in ValkeyCartStore.cs
      run: |
        FILE_PATH="src/cartservice/src/cartstore/ValkeyCartStore.cs"
        if grep -q 'ssl=false' $FILE_PATH; then
          sed -i 's/,ssl=false//' $FILE_PATH
        else
          sed -i 's/abortConnect=false/ssl=false,abortConnect=false/' $FILE_PATH
        fi
        git add $FILE_PATH
        git commit -m "Small code change to Redis"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
